peticiones.http
GET http://localhost:20044/player/getAll HTTP/1.1

###

GET http://localhost:20044/player/getOneById/1 HTTP/1.1

###
GET http://localhost:20044/player/getOneByEmail/gabi12345az.az2@gmail.com HTTP/1.1

###
POST http://localhost:20044/player/createOnePlayer HTTP/1.1
# content-type: application/json

# {
#     "Persona_ID": 1,
#     "Descripcion_Blog": "Carreras",
#     "Imagen": "",
# }

###
POST http://localhost:20044/player/updatePlayer/1 HTTP/1.1
# content-type: application/json

# {
#     "Persona_ID": 1,
#     "Descripcion_Blog": "Carreras",
#     "Imagen": "",
#     "Estatus": true
# }

###
GET http://localhost:20044/player/delPlayer/1 HTTP/1.1
